environment: "development"
log_level: "debug" # if environment is set to production, log_level will default to error

account:
  password_cost: 11
  confirm_token_expires: "24h00m"
  # confirm_token_endpoint:
  reset_password_token_expires: "1h00m"
  # reset_password_token_endpoint:

roles:
  define:
  - "admin"
  - "member"
  - "guest"
  default: "guest" # must exist in roles.define

serve:
  host: "localhost"
  port: 9096

token:
  # public_key_path:
  # private_key_path:
  issuer: "jwt-auth"
  access_token_expires: "5m"
  refresh_token_expires: "8h00m"
  refresh_token_expires_extended: "8760h00m"

postgres:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "jwt-auth"

amqp:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"

# email:
#   smtp_host:
#   smtp_port:
#   smtp_username:
#   smtp_password:
#   from_address:
#   from_name:
#   test_receipient:
