environment: "development"
log_level: "debug" # if environment is set to production, log_level will default to error
log_email: true    # if environment is set to production, log_email will default to false

account:
  password_cost: 11
  confirm_token_expires: "24h00m"
  reset_password_token_expires: "1h00m"

roles:
  define:
  - "admin"
  - "member"
  - "guest"
  default: "guest" # must exist in roles.define

serve:
  host: "localhost"
  port: 9096

cors:
  allow_all_origins: true
  allow_origins:
    - "http://localhost:8080"
  allow_credentials: false

token:
  # public_key_path:
  # private_key_path:
  issuer: "jwt-auth"
  access_token_expires: "5m"                 # recommended to keep this short (<10m)
  refresh_token_expires: "8h00m"
  refresh_token_expires_extended: "8760h00m" # if user selects remember me, this will be used

postgres:
  host: "localhost"
  port: 5432
  sslmode: "disable"
  username: "postgres"
  password: "postgres"
  database: "jwt-auth"

amqp:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"

# email:
#   smtp_host:
#   smtp_port:
#   smtp_username:
#   smtp_password:
#   from_address:
#   from_name:
#   test_receipient:
