environment: "development"
log_level: "debug" # if environment is set to production, log_level will default to error

serve:
  host: "localhost"
  port: 9096

token:
  # private_key_path:
  access_token_expires: "5m"
  refresh_token_expires: "1d"
  refresh_token_expires_extended: "1y"

postgres:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "jwt-auth"

# email:
#   smtp_host:
#   smtp_port:
#   smtp_username:
#   smtp_password:
#   from_address:
#   test_receipient:
