token:
  # private_key_path:
  access_token_expires: "5m"
  refresh_token_expires: "1d"
  refresh_token_expires_extended: "1y"

postgres:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "jwt-auth"
