environment: "production"
# log_level: # if environment is set to production, log_level will default to error

# roles:
#   define:
#   - "admin"
#   - "member"
#   - "guest"
#   default: "guest" # must exist in roles.define

# serve:
#   host: "localhost"
#   port: 9096

# token:
#   public_key_path:
#   private_key_path:
#   issuer: "jwt-auth"
#   access_token_expires: "5m"
#   refresh_token_expires: "8h00m"
#   refresh_token_expires_extended: "8760h00m"

# postgres:
#   host:
#   port:
#   username:
#   password:
#   database:

# amqp:
#   host:
#   port:
#   username:
#   password:

# email:
#   smtp_host:
#   smtp_port:
#   smtp_username:
#   smtp_password:
#   from_address:
#   from_name:
#   test_receipient:
