environment: "production"

# token:
#   private_key_path:
#   access_token_expires: "5m"
#   refresh_token_expires: "1d"
#   refresh_token_expires_extended: "1y"

# postgres:
#   host:
#   port:
#   username:
#   password:
#   database:

# email:
#   smtp_host:
#   smtp_port:
#   smtp_username:
#   smtp_password:
#   from_address:
#   test_receipient:
